export interface MsoProperty {
  property: string;
  values: string[];
  default: string | number | null;
  inherits: boolean;
}

const msoProperties: MsoProperty[] = [
  {
    property: 'font-color',
    values: [],
    default: null,
    inherits: false,
  },
  {
    property: 'horiz-align',
    values: ['center', 'left', 'right'],
    default: null,
    inherits: false,
  },
  {
    property: 'list-image-1',
    values: ['<url>'],
    default: null,
    inherits: false,
  },
  {
    property: 'list-image-2',
    values: ['<url>'],
    default: null,
    inherits: false,
  },
  {
    property: 'list-image-3',
    values: ['<url>'],
    default: null,
    inherits: false,
  },
  {
    property: 'mso-ansi-font-size',
    values: [
      'large',
      'larger',
      '<length>',
      'medium',
      '<percentage>',
      'small',
      'smaller',
      'x-large',
      'x-small',
      'xx-large',
      'xx-small',
    ],
    default: 'medium',
    inherits: true,
  },
  {
    property: 'mso-ansi-font-style',
    values: ['italic', 'normal', 'oblique'],
    default: 'normal',
    inherits: true,
  },
  {
    property: 'mso-ansi-font-weight',
    values: ['bold', 'bolder', 'lighter', 'normal', '<number>'],
    default: 'normal',
    inherits: true,
  },
  {
    property: 'mso-ansi-language',
    values: ['<string>'],
    default: null,
    inherits: true,
  },
  {
    property: 'mso-ascii-font-family',
    values: ['auto', 'cursive', 'fantasy', 'monospace', 'sans-serif', 'serif', '<string>'],
    default: null,
    inherits: true,
  },
  {
    property: 'mso-background',
    values: ['auto', '<color>', 'windowtext'],
    default: null,
    inherits: false,
  },
  {
    property: 'mso-background-source',
    values: ['auto'],
    default: null,
    inherits: false,
  },
  {
    property: 'mso-baseline-position',
    values: ['<percentage>'],
    default: null,
    inherits: false,
  },
  {
    property: 'mso-bidi-flag',
    values: ['off', 'on'],
    default: 'off',
    inherits: true,
  },
  {
    property: 'mso-bidi-font-family',
    values: ['auto', 'cursive', 'fantasy', 'monospace', 'sans-serif', 'serif', '<string>'],
    default: null,
    inherits: true,
  },
  {
    property: 'mso-bidi-font-size',
    values: [
      '<length>',
      '<percentage>',
      'large',
      'larger',
      'medium',
      'small',
      'smaller',
      'x-large',
      'x-small',
      'xx-large',
      'xx-small',
    ],
    default: 'medium',
    inherits: true,
  },
  {
    property: 'mso-bidi-font-style',
    values: ['italic', 'normal', 'oblique'],
    default: 'normal',
    inherits: true,
  },
  {
    property: 'mso-bidi-font-weight',
    values: ['bold', 'bolder', 'lighter', 'normal', '<number>'],
    default: 'normal',
    inherits: true,
  },
  {
    property: 'mso-bidi-language',
    values: ['<string>'],
    default: null,
    inherits: true,
  },
  {
    property: 'mso-bookmark',
    values: ['<string>'],
    default: null,
    inherits: false,
  },
  {
    property: 'mso-border-alt',
    values: [
      'apples',
      'arched-scallops',
      'auto',
      'baby-pacifier',
      'baby-rattle',
      'balloons-3-colors',
      'balloons-hot-air',
      'basic-black-dashes',
      'basic-black-dots',
      'basic-black-squares',
      'basic-thin-lines',
      'basic-white-dashes',
      'basic-white-dots',
      'basic-white-squares',
      'basic-wide-inline',
      'basic-wide-midline',
      'basic-wide-outline',
      'bats',
      'birds',
      'birds-flight',
      'cabins',
      'cake-slice',
      'candy-corn',
      'celtic-knotwork',
      'certificate-banner',
      'chain-link',
      'champagne-bottle',
      'checked-bar-black',
      'checked-bar-color',
      'checkered',
      'christmas-tree',
      'circles-lines',
      'circles-rectangles',
      'classical-wave',
      'clocks',
      '<color>',
      'compass',
      'confetti',
      'confetti-grays',
      'confetti-outline',
      'confetti-streamers',
      'confetti-white',
      'corner-triangles',
      'coupon-cutout-dashes',
      'coupon-cutout-dots',
      'crazy-maze',
      'creatures-butterfly',
      'creatures-fish',
      'creatures-insects',
      'creatures-lady-bug',
      'cross-stitch',
      'cup',
      'dash-dot-stroked',
      'dashed',
      'dash-large-gap',
      'dash-small-gap',
      'deco-arch',
      'deco-arch-color',
      'deco-blocks',
      'diamonds-gray',
      'dot-dash',
      'dot-dash-slanted',
      'dot-dot-dash',
      'dotted',
      'double',
      'double-d',
      'double-diamonds',
      'double-wave',
      'earth-1',
      'earth-2',
      'eclipsing-squares-1',
      'eclipsing-squares-2',
      'eggs-black',
      'emboss-3d',
      'engrave-3d',
      'fans',
      'film',
      'firecrackers',
      'flowers-block-print',
      'flowers-daisies',
      'flowers-modern-1',
      'flowers-modern-2',
      'flowers-pansy',
      'flowers-red-rose',
      'flowers-roses',
      'flowers-teacup',
      'flowers-tiny',
      'gems',
      'gingerbread-man',
      'gradient',
      'groove',
      'hairline',
      'handmade-1',
      'handmade-2',
      'heart-balloon',
      'heart-gray',
      'hearts',
      'heebie-jeebies',
      'holly',
      'house-funky',
      'hypnotic',
      'ice-cream-cones',
      'inset',
      '<length>',
      'light-bulb',
      'lightning-1',
      'lightning-2',
      'maple-leaf',
      'maple-muffins',
      'map-pins',
      'marquee',
      'marquee-toothed',
      'medium',
      'moons',
      'mosaic',
      'music-notes',
      'none',
      'northwest',
      'outset',
      'ovals',
      'packages',
      'palms-black',
      'palms-color',
      'paper-clips',
      'papyrus',
      'party-favor',
      'party-glass',
      'pencils',
      'people',
      'people-hats',
      'people-waving',
      'poinsettias',
      'postage-stamp',
      'pumpkin-1',
      'push-pin-note-1',
      'push-pin-note-2',
      'pyramids',
      'pyramids-above',
      'quadrants',
      'ridge',
      'rings',
      'safari',
      'sawtooth',
      'sawtooth-gray',
      'scared-cat',
      'seattle',
      'shadowed-squares',
      'sharks-teeth',
      'shorebird-tracks',
      'short-dash',
      'skyrocket',
      'snowflake-fancy',
      'snowflakes',
      'solid',
      'solid-thick',
      'sombrero',
      'southwest',
      'stars',
      'stars-3d',
      'stars-black',
      'stars-shadowed',
      'stars-top',
      'sun',
      'swirligig',
      'thick',
      'thick-thin-large-gap',
      'thick-thin-medium-gap',
      'thick-thin-small-gap',
      'thick-thin-thick-small-gap',
      'thin',
      'thin-thick-large-gap',
      'thin-thick-medium-gap',
      'thin-thick-small-gap',
      'thin-thick-thin-large-gap',
      'thin-thick-thin-medium-gap',
      'thin-thick-thin-small-gap',
      'three-d-emboss',
      'three-d-engrave',
      'torn-paper',
      'torn-paper-black',
      'trees',
      'triangle-party',
      'triangles',
      'tribal-1',
      'tribal-2',
      'tribal-3',
      'tribal-4',
      'tribal-5',
      'tribal-6',
      'triple',
      'twisted-lines-1',
      'twisted-lines-2',
      'vine',
      'wave',
      'waveline',
      'weaving-angles',
      'weaving-braid',
      'weaving-ribbon',
      'weaving-strips',
      'white-flowers',
      'windowtext',
      'woodwork',
      'x-illusions',
      'zany-triangles',
      'zig-zag',
      'zig-zag-stitch',
    ],
    default: null,
    inherits: false,
  },
];

export default msoProperties;
